version: "3.8"  # optional since v1.27.0
services:
    my-mysql:
        image: mysql:8.0.1
        deploy: 
            replicas: 2
        networks:
            - conexion-network
        environment:
            MYSQL_USER: admin
            MYSQL_DATABASE: clientes
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '3306:3306'
                 
    mybackend-x:
        image: criszhirzhan/backend
        deploy: 
            replicas: 2
        ports:
            - "9090:9090"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/clientes?useSSL=false
            SPRING_DATASOURCE_USERNAME: "admin"
            SPRING_DATASOURCE_PASSWORD: "admin"
        depends_on:
            - my-mysql
        networks:
            - conexion-network 
        hostname: backend
    
    myfrontend-x-2:
        image: criszhirzhan/frontend
        deploy: 
            replicas: 2
        ports:
            - "5555:80"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/clientes?useSSL=false
            SPRING_DATASOURCE_USERNAME: "admin"
            SPRING_DATASOURCE_PASSWORD: "admin"
        depends_on:
            - my-mysql
        networks: 
            - conexion-network
        hostname: frontend

networks: 
    conexion-network: